services:
  redis-cache:
    image: redis:7-alpine
    container_name: redis-blacklist
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - secure-devops-net

  rabbitmq-mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - secure-devops-net

  ml-engine:
    build: ./ml-analysis-engine
    container_name: ml-analysis-engine
    environment:
      - REDIS_HOST=redis-cache
      - RABBITMQ_HOST=rabbitmq-mq
    depends_on:
      redis-cache:
        condition: service_healthy
      rabbitmq-mq:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - secure-devops-net

  log-generator:
    build:
      context: ./log-generator
      dockerfile: Dockerfile.ui
    container_name: log-generator
    environment:
      - RABBITMQ_HOST=rabbitmq-mq
    ports:
      - "8501:8501"
    depends_on:
      ml-engine:
        condition: service_started
    restart: on-failure
    networks:
      - secure-devops-net

  prometheus-core:
    image: prom/prometheus:v2.45.0
    container_name: prometheus-core
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - ml-engine
    networks:
      - secure-devops-net

  grafana-visual-soc:
    image: grafana/grafana:10.0.0
    container_name: grafana-visual-soc
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus-core
    networks:
      - secure-devops-net

networks:
  secure-devops-net:
    driver: bridge