FROM python:3.10-slim
WORKDIR /app
RUN pip install --no-cache-dir pika streamlit requests pandas
COPY app.py .
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--browser.gatherUsageStats=false"]