name: DevSecOps Automation Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  sast-security-audit:
    name: Code Vulnerability Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Code Repository Check out
        uses: actions/checkout@v4

      - name: Set up Environment Run-time
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Linting Tools
        run: pip install flake8 bandit

      - name: Evaluate Python Code Hygiene
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Execute Security Scan (Bandit SAST)
        run: bandit -r ./ml-analysis-engine ./log-generator

  orchestration-audit:
    name: Infrastructure Manifest Validation
    needs: sast-security-audit
    runs-on: ubuntu-latest
    steps:
      - name: Code Repository Check out
        uses: actions/checkout@v4

      - name: Validate Compose File Properties
        run: docker compose config